Add a fuzzy search on tilelayers
jupyterlab/jupyter-renderers pull request #278
Opened 2022-06-28 10:08 UTC by HaudinFlorence

2022-07-04 07:41 UTC, davidbrochart requested changes
You don't seem to use `packages/geojson-extension/style/icons/layers-16px.svg`, are you sure you want to commit it?

2022-07-04 07:41 UTC, davidbrochart commented on packages/geojson-extension/src/index.ts
> +    if (name !== undefined && nameList.includes(name) === false) {
```suggestion
    if (name !== undefined && !nameList.includes(name)) {
```

2022-07-04 07:41 UTC, davidbrochart commented on packages/geojson-extension/src/index.ts
> +      if (name !== undefined && nameList.includes(name) === false) {
```suggestion
      if (name !== undefined && !nameList.includes(name)) {
```

2022-07-04 07:41 UTC, davidbrochart commented on packages/geojson-extension/src/index.ts
> +   * The indices of the matched characters.
This description doesn't seem to match.

2022-07-04 07:41 UTC, davidbrochart commented on packages/geojson-extension/src/index.ts
> +          console.log('result.value: ', result.value);
Leftover?

2022-07-04 08:14 UTC, davidbrochart commented
I would be nice to have the fuzzy search show all results before entering some text, so that we know what base maps are available. Currently it shows nothing until we start typing.

2022-07-04 08:16 UTC, davidbrochart commented
Also, maybe display the base map for OpenStreetMap by default?

2022-07-04 08:51 UTC, HaudinFlorence commented
> I would be nice to have the fuzzy search show all results before entering some text, so that we know what base maps are available. Currently it shows nothing until we start typing.

I totally agree. I tried to do it but without any success. I tried to display the select list prior to use the eventhandler and to perform any fuzzy search, but the results was not as expected : I could not see more that one element of the list even when asking the size to be a given number and the css style was not applied.

2022-07-04 08:54 UTC, HaudinFlorence commented
> Also, maybe display the base map for OpenStreetMap by default?

That's possible.

2022-07-04 10:15 UTC, davidbrochart approved these changes
Thanks for the changes @HaudinFlorence.

A couple of potential improvements:
- When the API key is wrong, nothing happens. Maybe we could catch the errors and notify the user?

https://user-images.githubusercontent.com/4711805/177133822-696e5057-c46d-425b-bd1f-be7270286bae.mp4

- Some maps are not available, maybe worth removing them?

https://user-images.githubusercontent.com/4711805/177133838-8095a1ea-4fec-425a-89c4-ddd6af200550.mp4

2022-07-04 10:15 UTC, davidbrochart commented on packages/geojson-extension/src/access_data.json
> +  },
Then maybe no need for `"keyString"`?
```suggestion
  "Thunderforest": "apikey",
```

2022-07-04 10:15 UTC, davidbrochart commented on packages/geojson-extension/src/index.ts
> +                body: new TextInput('Enter the APIkey please'),
```suggestion
                body: new TextInput('Enter the API key please'),
```

2022-07-04 10:16 UTC, davidbrochart commented
> I would be nice to have the fuzzy search show all results before entering some text, so that we know what base maps are available. Currently it shows nothing until we start typing.

Should be fixed in https://github.com/HaudinFlorence/jupyter-renderers/pull/2.

2022-07-04 14:46 UTC, HaudinFlorence commented
> Thanks for the changes @HaudinFlorence.
> 
> A couple of potential improvements:
> 
> * When the API key is wrong, nothing happens. Maybe we could catch the errors and notify the user?
> 
>  georenderer.mp4 
> * Some maps are not available, maybe worth removing them?
> 
>  georenderer2.mp4

Thanks for the suggestions. It would be indeed better to have an error message when the API key is wrong. It would also be worthy to remove the tilelayers that are not available.

2022-07-04 15:52 UTC, HaudinFlorence commented on packages/geojson-extension/src/access_data.json
> +  },
keyString has been removed.

2022-07-04 15:53 UTC, HaudinFlorence commented on packages/geojson-extension/src/index.ts
> +                body: new TextInput('Enter the APIkey please'),
This has been changed.

2022-07-04 15:55 UTC, HaudinFlorence commented
> > I would be nice to have the fuzzy search show all results before entering some text, so that we know what base maps are available. Currently it shows nothing until we start typing.
> 
> Should be fixed in [HaudinFlorence#2](https://github.com/HaudinFlorence/jupyter-renderers/pull/2).

Thanks for the suggestion. This will be added.

2022-07-05 13:51 UTC, davidbrochart commented on packages/geojson-extension/src/index.ts
> +              layer.addTo(this._map);
It looks like layers are never removed from the map, so if the user chooses a base map and then another one, (unnecessary) requests will be made to the previous base map.

2022-07-05 13:51 UTC, davidbrochart commented on packages/geojson-extension/src/index.ts
> +          !name.includes('HERE.')
Should we directly remove these base maps from `providers.json`?

2022-07-06 07:55 UTC, HaudinFlorence commented on packages/geojson-extension/src/index.ts
> +              layer.addTo(this._map);
> It looks like layers are never removed from the map, so if the user chooses a base map and then another one, (unnecessary) requests will be made to the previous base map.

Yes the layers are not removed the way the code is written now. Do you suggest to remove the previous basemap before trying to add a new one ?

2022-07-07 08:44 UTC, davidbrochart commented on packages/geojson-extension/src/index.ts
> +                console.log('url :', tilelayers_data[APIname].url);
Leftover?

2022-07-07 13:34 UTC, jtpio commented on packages/geojson-extension/src/index.ts
> +    this._query.placeholder = 'Enter your query';
Maybe something like `Search for a tile layer` would be more specific?

2022-07-07 13:35 UTC, jtpio commented on packages/geojson-extension/src/index.ts
> +export class TilelayerPalette
Looks like this one is usually spelled `TileLayer` with a capital `L`, for example in Leaflet. Maybe we can keep the same style here and in other places?

2022-07-07 13:43 UTC, jtpio commented on packages/geojson-extension/style/base.css
> +.select-list {
Wondering if these classes could be more narrowly scoped to only apply to the geojson view, for example `.jp-RenderedGeoJSON`.

2022-07-07 13:49 UTC, jtpio commented
Thanks @HaudinFlorence for working on this :+1: 

This might be similar to the comment above, but it looks like some layers don't prompt for an API key. For example:

https://user-images.githubusercontent.com/591645/177789721-4fe66f40-2671-43c0-88f1-36b32d014ff3.mp4

2022-07-07 15:02 UTC, HaudinFlorence commented on packages/geojson-extension/src/index.ts
> +    this._query.placeholder = 'Enter your query';
Thanks for the comment. This has been changed.

2022-07-07 15:04 UTC, HaudinFlorence commented
> Thanks @HaudinFlorence for working on this +1
> 
> This might be similar to the comment above, but it looks like some layers don't prompt for an API key. For example:
> 
>  geojson-layers.mp4

I checked precisely for this tile layer and it seems to work from side, at least locally.

2022-07-11 17:09 UTC, HaudinFlorence commented
> Thanks @HaudinFlorence for working on this +1
> 
> This might be similar to the comment above, but it looks like some layers don't prompt for an API key. For example:
> 
>  geojson-layers.mp4

Thank you very much for your comments and review :+1: @davidbrochart @jtpio

2022-07-11 17:27 UTC, HaudinFlorence commented on packages/geojson-extension/src/index.ts
> +                console.log('url :', tilelayers_data[APIname].url);
This has been addressed. Thank you very much for your review @davidbrochart

2022-11-09 08:45 UTC, fcollonval commented on packages/geojson-extension/style/icons/layers-32px.svg
> +</g>
> Hint when using Inkscape, you can use `Save As -> Optimized SVG` to get a first lighter file. Then I finish to clean up the file manually.

2022-11-09 08:52 UTC, fcollonval requested changes
Minor comments on the packaging

2022-11-09 08:52 UTC, fcollonval commented on packages/geojson-extension/package.json
>      "style/*.*",
That should be enough to include everything in the `style` folder:

```suggestion
    "style/**/*",
```

2022-11-09 08:52 UTC, fcollonval commented on packages/geojson-extension/package.json
> +    "src/providers.json"
```suggestion
    "src/*.json"
```

2022-11-09 09:44 UTC, HaudinFlorence commented on packages/geojson-extension/style/icons/layers-32px.svg
> +</g>
Thanks for the comment and hint. A new version of the svg file is proposed in commit f763dea, generated with `Save As -> Optimized SVG` using Inkscape.

2022-11-10 07:51 UTC, fcollonval approved these changes
Thanks @HaudinFlorence

2022-11-10 07:52 UTC, merged

2022-11-10 09:08 UTC, HaudinFlorence commented
Thanks for merging merging @fcollonval